version: '3.8'

services:
  app:
    build: .
    environment:
      NODE_ENV: development
      RAPIDS_URL: rapids:9092
    networks:
      - services-network
    volumes:
      - ./:/app

networks:
  services-network:
    name: services-network
