version: '3.8'

services:
  index:
    build: ./index
    environment:
      NODE_ENV: development
      RAPIDS_URL: rapids:9092
    networks:
      - services-network
    volumes:
      - ./index:/app

networks:
  services-network:
    name: services-network
