version: '3.8'

services:
  app:
    build: .
    environment:
      NODE_ENV: development
    networks:
      - services-network
    volumes:
      - ./:/app

networks:
  services-network:
    name: services-network
