version: '3.8'

services:
  app:
    build: ./services/client
    depends_on:
      - sockets
    environment:
      NODE_ENV: development
      PORT: 8080
      VUE_APP_RAPIDS_PROXY_URL: http://localhost:8082/
    networks:
      - services-network
    ports:
      - 8080:8080
    volumes:
      - ./services/client:/app

  producer:
    build: ./services/producer
    environment:
      NODE_ENV: development
      PORT: 8081
    networks:
      - services-network
    ports:
      - 8081:8081
    volumes:
      - ./services/producer:/app

networks:
  services-network:
    name: services-network
