version: '3.8'

services:
  app:
    build: ./services/client
    environment:
      NODE_ENV: development
      PORT: 8080
      VUE_APP_RAPIDS_PROXY_URL: http://localhost:8082/
    networks:
      - services-network
    ports:
      - 8080:8080
    volumes:
      - ./services/client:/app

networks:
  services-network:
    name: services-network
