version: '3.8'

services:
  client:
    build: ./services/client
    depends_on:
      - client-h
    environment:
      NODE_ENV: development
      PORT: 8080
      VUE_APP_CLIENT_H_URL: http://localhost:8081/
    networks:
      - services-network
    ports:
      - 8080:8080
    volumes:
      - ./services/client:/app

  client-h:
    build: ./services/client-h
    depends_on:
      - redis
    environment:
      NODE_ENV: development
      PORT: 8081
      RAPIDS_URL: rapids:9092
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - services-network
    ports:
      - 8081:8081
    volumes:
      - ./services/client-h:/app

  redis:
    image: bitnami/redis-cluster:5.0.9
    environment:
      REDIS_PORT: 6379
    networks:
      - services-network
    ports:
      - 6379:6379

networks:
  services-network:
    name: services-network
