version: '3.8'

services:
  app:
    build: ./services/client
    depends_on:
      - producer
      - subscriber
    environment:
      NODE_ENV: development
      PORT: 8080
      VUE_APP_PRODUCER_URL: http://localhost:8081/
      VUE_APP_SUBSCRIBER_URL: http://localhost:8083/
    networks:
      - services-network
    ports:
      - 8080:8080
    volumes:
      - ./services/client:/app

  producer:
    build: ./services/producer
    depends_on:
      - redis
    environment:
      NODE_ENV: development
      PORT: 8081
      RAPIDS_URL: rapids:9092
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - services-network
    ports:
      - 8081:8081
    volumes:
      - ./services/producer:/app

  redis:
    image: bitnami/redis-cluster:5.0.9
    environment:
      REDIS_PORT: 6379
    networks:
      - services-network
    ports:
      - 6379:6379

  subscriber:
    build: ./services/subscriber
    depends_on:
      - redis
    environment:
      NODE_ENV: development
      PORT: 8083
      RAPIDS_URL: rapids:9092
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - services-network
    ports:
      - 8083:8083
    volumes:
      - ./services/subscriber:/app

networks:
  services-network:
    name: services-network
