version: '3'

services:
  client:
    build: .
    command: "npm run dev"
    environment:
      NODE_ENV: development
    ports:
      - 8080:8080
    volumes:
      - ./:/app

networks:
  default:
    external:
      name: services-network
