version: '3.8'

services:
  app:
    build: .
    environment:
      NODE_ENV: development
      PORT: 8080
      RAPIDS_PROXY_URL: http://localhost:8082/
    networks:
      - services-network
    ports:
      - 8080:8080
    volumes:
      - ./:/app

networks:
  services-network:
    name: services-network
